services:
  whoami:
    image: traefik/whoami:v1.10
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
